name: Setup Multipass
description: Set up Multipass on a GitHub runner
inputs:
  wait:
    description: Wait for Multipass to complete install and startup
    default: true

runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo snap install multipass
        sudo chown "${USER}:$(groups | cut -d' ' -f1)" /var/snap/multipass/common/multipass_socket
    - if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        curl -o ${{ runner.temp }}/multipass.pkg -L https://canonical.com/multipass/download/macos
        sudo installer -pkg ${{ runner.temp }}/multipass.pkg -target /
    - if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        curl -o ${{ runner.temp }}/multipass.msi -L https://canonical.com/multipass/download/windows
        msiexec.exe /a "${{ runner.temp }}/multipass.msi" /quiet /norestart
    - if: ${{ inputs.wait == 'true' }}
      shell: bash
      run: |
        echo Waiting until Multipass is up...
        while ! multipass list; do
          sleep 1
        done
        echo Updating multipass remotes...
        multipass find --force-update
