name: Setup Multipass
description: Set up Multipass on a GitHub runner
inputs:
  wait:
    description: Wait for Multipass to complete install and startup
    default: true

runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo snap install multipass
        sudo chown "${USER}:$(groups | cut -d' ' -f1)" /var/snap/multipass/common/multipass_socket
    - if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install --cask multipass
    - if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        curl -o ${{ runner.temp }}\multipass.msi -L https://canonical.com/multipass/download/windows
        Start-Process msiexec.exe -Wait -ArgumentList "/i", "$($ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("${{ runner.temp }}\multipass.msi"))", "/quiet", "/norestart"
        $paths = @("C:\Program Files\Multipass\bin", "C:\Program Files\Multipass")
        foreach ($path in $paths) {
          if (Test-Path $path) {
            echo "$path" >> $env:GITHUB_PATH
            break
          }
        }
    - if: ${{ inputs.wait == 'true' }}
      shell: bash
      run: |
        echo Waiting until Multipass is up...
        while ! multipass list; do
          sleep 1
        done
        echo Updating multipass remotes...
        multipass find --force-update
    - if: ${{ runner.os == 'macOS' }}
      name: Configure runner to run multipass as root
      # Workaround for https://github.com/canonical/multipass/issues/4588
      shell: bash
      run: |
        multipass_passphrase=$(uuidgen)
        sudo multipass set local.passphrase=$multipass_passphrase
        while ! sudo multipass authenticate $multipass_passphrase; do
          sleep 1
        done
        MULTIPASS_BIN=$(which multipass)
        sudo mv "$MULTIPASS_BIN" "${MULTIPASS_BIN}-real"
        printf "#!/bin/bash\nexec /usr/bin/sudo -E \"${MULTIPASS_BIN}-real\" \"\$@\"" | sudo tee "$MULTIPASS_BIN"
        sudo chmod a+x "$MULTIPASS_BIN"
